-- ⚠ Not authoritative. The schema is now defined by versioned migrations.
--
-- The source of truth is packages/db/src/migrations/. The full baseline schema
-- lives in migrations/0001_init.sql; later changes are additional numbered files,
-- applied forward-only by the runner in migrate.ts (recorded in schema_migrations).
--
-- This file is kept only as a signpost so older links don't dead-end. Do not add
-- schema here — add a new migration instead.
